<a href="https://colab.research.google.com/github/VAEH/fundamentos_datos/blob/main/Prueba_2_LLV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Prueba #2**
En la siguiente pureba se evalua de manera EXCLUSIVA lo que se solicita, cualquier otra respuesta adicional a ella será valorada, más no evaluada. Entregue la prueba en un repositorio de github antes de el domingo 18 de Febrero a las 23:59:59.

### Participantes
- Leidy Jaramillo Parra
- Lucero Zarate Herrera
- Víctor Echavarría Hernandez

## **Ejercicio 1** (40%)

Construya un DataFrame a partir del siguiente diccionario

`exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 10, 9, 20, 14.5, 12, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}`

con las siguientes etiquetas para los índices

`labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']`

1. Seleccione solo las columnas *name* y *score*.
  
2. Filtre las filas donde el número de intentos (attemps) sea mayor que 2.

3. Filtre las filas donde el *score* se encuentre entre 15 y 20 (incluidos)

4. Cambie el *score* en la fila 'd' a 11.5

5. Agregue una nueva fila con etiqueta 'k' al dataframe con un valor que usted desee para cada columna

6. Borre la fila 'k' y entregue nuevamente el DataFrame original.

7. Ordene el DataFrame por nombre en orden ascendente.

8. Reemplace los valores de la columna *qualify* que contiene los valores *yes* y *no* por los valores booleanos True y False respectivamente.

In [1]:
import pandas as pd

# Diccionario de datos
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, 10, 9, 20, 14.5, 12, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

# Etiquetas para los índices
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Construir DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Mostrar DataFrame
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   10.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   12.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [2]:
# seleccionamos las columnas name y score para esto utilizamos la notación de corchetes para acceder a las dos columnas específicas del df
selected_columns= df[['name','score']]
print(selected_columns)

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James   10.0
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura   12.0
i      Kevin    8.0
j      Jonas   19.0

In [3]:
#Filtramos las filas donde el número de intentos (attemps) sea mayor que 2
#Utilizamos loc para acceder a un grupo de filas a través de etiquetas o matriz booleana

filtered_attemps= df.loc[df['attempts'] > 2]
print(filtered_attemps)

#df.loc[df['attempts'] > 2] utiliza esta serie booleana como una máscara para seleccionar las filas donde la condición sea verdadera

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James   10.0         3      no
f  Michael   20.0         3     yes

In [4]:
#Filtramos las filas donde el score se encuentre entre 15 y 20 (incluidos)
#volvemos a utilizar una máscara booleana para seleccionar las filas donde la condición sea verdadera (esta vez la condición conlleva un & y se utiliza el operador = para que sea incluyente)
filtered_score= df.loc[(df['score']>=15)&(df['score']<=20)]
print(filtered_score)

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

In [5]:
#Cambiamos el score en la fila 'd' a 11.5
#Utilizamos loc para acceder a una fila específica por su índice y luego asignamos el valor dado en la columna score
df.loc['d','score']=11.5
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   12.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [6]:
# Agregamos una nueva fila con etiqueta 'k' al dataframe con un valor deseado para cada columna
df.loc['k'] = ['Lucia', 15.0, 2, 'yes']
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   12.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k      Lucia   15.0         2     yes

In [7]:
#Borramos la fila 'k' con el método drop de pandas y entregamos nuevamente el DataFrame original
df= df.drop('k')
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura   12.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [8]:
# Ordenamos el DataFrame por nombre en orden ascendente mediante el método sort_values que por defecto tiene el parámetro ascending en True
df_sorted = df.sort_values(by='name')
print(df_sorted)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   11.5         3      no
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
i      Kevin    8.0         2      no
h      Laura   12.0         1      no
g    Matthew   14.5         1     yes
f    Michael   20.0         3     yes

In [9]:
#Reemplazamos los valores de la columna qualify que contiene los valores yes y no por los valores booleanos True y False respectivamente
#Creamos un diccionario de mapeo de valores
#En pandas el mapeo se utiliza para cambiar los valores en una serie según un diccionario o una función
mapping = {'yes': True, 'no': False}

# Aplicamos el mapeo a la columna 'qualify'
df['qualify'] = df['qualify'].map(mapping)
print(df)

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James   11.5         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura   12.0         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

## **Ejercicio 2** (30%)

Importe el dataset `athletes` del repositorio del curso y realice las siguientes tareas:

1. Importarlo como nombre athletes
2. Filtre el dataframe tal que solo se quede con los atletas que hayan ganado al menos una medalla.
3. Calcule la masa muscular por fila con una función como

$$I_{m.m.} = \frac{Weight}{Height^2}$$

4. Agrupe los datos por calculando la media por deporte para cada una del resto de características. ¿Cuál es el deporte en el que los jugadores tienen mayor peso promedio?

5. ¿Cuál es el pais con más participación femenina?

In [ ]:
import pandas as pd

In [ ]:
nombre_atlethes = pd.read_csv('/content/athletes.csv')
nombre_atlethes.head(2)

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze
0,736041664,A Jesus Garcia,ESP,male,10/17/69,1.72,64.0,athletics,0,0,0
1,532037425,A Lam Shin,KOR,female,9/23/86,1.68,56.0,fencing,0,0,0

In [ ]:
# Filtro en el que al menos haya tenido una medalla de oro, plata o bronze
filtro = (nombre_atlethes['gold'] >= 1) | nombre_atlethes['silver'] >= 1 | (nombre_atlethes['bronze'] >= 1)
nombre_atlethes = nombre_atlethes.loc[filtro]
nombre_atlethes.sample(5)

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze
9687,558359788,Sergio Dutra Santos,BRA,male,10/15/75,1.84,78.0,volleyball,1,0,0
4551,507019886,Jake Kaminski,USA,male,8/11/88,1.78,70.0,archery,0,1,0
949,711366566,Anna Korakaki,GRE,female,4/8/96,1.75,65.0,shooting,1,0,1
8657,229176554,Philip Hindes,GBR,male,9/22/92,1.78,82.0,cycling,1,0,0
7099,408549485,Maryia Mamashuk,BLR,female,8/31/92,1.63,65.0,wrestling,0,1,0

In [ ]:
def masa_muscular(height, weight):
  """
  Funcion que permite calcular la masa muscula apartir del peso y la altura

  params:
  height(float): Altura
  weight(float): Peso

  Return
  Masa corporal
  """
  masam = weight/(height**2)
  return masam

# Crea una nueva columna `masa_corporal`
nombre_atlethes['masa_corporal'] = nombre_atlethes.apply(lambda row: masa_muscular(row['height'],
                                                                                   row['weight']),
                                                         axis=1)
# Devuelve una muestra
nombre_atlethes.sample(3)

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze,masa_corporal
1717,59463747,Cameron van der Burgh,RSA,male,5/25/88,1.85,85.0,aquatics,0,1,0,24.835646
4795,528202320,Jeremy Stravius,FRA,male,7/14/88,1.90,87.0,aquatics,0,1,0,24.099723
4723,984646645,Jean-Paul Tony Helissey,FRA,male,3/28/90,1.77,77.0,fencing,0,1,0,24.577867

In [ ]:
# Calculo de peso promedio por deporte
media_peso_deporte = nombre_atlethes.groupby('sport')['weight'].mean().sort_values(ascending= False)
media_peso_deporte.head(3) # Imprime una muestra

# Deporte con jugadores con mayor peso promedio
media_peso_deporte.idxmax()

'basketball'

In [ ]:
# Filtra las atletas mujeres y agrupa por nacionalidad. Obtiene el país con más mujeres
nombre_atlethes[nombre_atlethes.sex == 'female'].groupby('nationality')['sex'].agg('count').idxmax()

'USA'

## **Ejercicio 3 (30%)**

Importe el dataset de nba del repositorio de clase y responda (hint: Elimine las instancias con registros faltantes):

1. Cuáles son los equipos que pagan los salarios más altos (presente el resultado como un dataFrame con el nombre del equipo y la cantidad de dinero de la nómina)
2. Separe la variable *Age* en tres grupos y cree una nueva columna llamada *Age-Group* con esta información.<
3. Construya una tabla dinámica que muestre el salario promedio de los jugadores por equipo y posición para para los cinco equipos que pagan mejores salarios.

In [ ]:
import pandas as pd

In [ ]:
#Importamos los datos que vamos a necesitar y los definimos como la data
data=pd.read_csv("https://raw.githubusercontent.com/tomasate/Datos_Clases/main/Datos_1/nba.csv")
data.head(10)

,Unnamed: 0,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [ ]:
#Eliminamos las filas que tienen registros faltantes en cualquiera de las columnas
df= data.dropna()
df

,Unnamed: 0,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
...,...,...,...,...,...,...,...,...,...,...
449,449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [ ]:
#Mostramos los 10 salarios mas altos
df= df.sort_values('Salary', ascending=False)
topsalario=df.loc[:,['Team','Salary']].head(10)
topsalario

                      Team      Salary
33         New York Knicks  22875000.0
339             Miami Heat  22192730.0
100   Los Angeles Clippers  21468695.0
414  Oklahoma City Thunder  20158622.0
164          Chicago Bulls  20093064.0
349             Miami Heat  20000000.0
174    Cleveland Cavaliers  19689000.0
294      San Antonio Spurs  19689000.0
98    Los Angeles Clippers  19689000.0
23           Brooklyn Nets  19689000.0

In [ ]:
#Ahora veremos como se comportan de acuerdo a los rangos de edad.
df["Age_Group"]=pd.cut(df.Age, bins = 3)
df

,Unnamed: 0,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Age_Group
33,33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0,"(26.0, 33.0]"
339,339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0,"(26.0, 33.0]"
100,100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0,"(26.0, 33.0]"
414,414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0,"(26.0, 33.0]"
164,164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0,"(26.0, 33.0]"
...,...,...,...,...,...,...,...,...,...,...,...
92,92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,6-9,250.0,Arizona State,111444.0,"(26.0, 33.0]"
175,175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196.0,"(18.979, 26.0]"
135,135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0,"(18.979, 26.0]"
291,291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722.0,"(26.0, 33.0]"
130,130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722.0,"(18.979, 26.0]"

In [ ]:
#para crear la tabla dinamica con promedio de salarios por equipo y posición, extraemos los cinco equipos que mejor salario pagan.
#Ordenamos los salarios

df.sort_values(by='Salary', ascending=False, inplace=True)

# Tomar los cinco primeros equipos
equipos_top5 = df['Team'].head(5).tolist()
equipos_top5

['New York Knicks',
 'Miami Heat',
 'Los Angeles Clippers',
 'Oklahoma City Thunder',
 'Chicago Bulls']

In [ ]:
#Filtramos el dataframe original por los equipos que están dentro del top 5 y creamos la tabla dinámica que nos permite conocer el salario
#promedio por equipo y posición

tabla_dinamica = df[df['Team'].isin(equipos_top5)].pivot_table(
    index=['Team', 'Position'],
    values='Salary',
    aggfunc='mean')

tabla_dinamica

                                      Salary
Team                  Position
Chicago Bulls         C         1.340000e+07
                      PF        3.578740e+06
                      PG        1.117153e+07
                      SF        1.958160e+06
                      SG        5.717549e+06
Los Angeles Clippers  C         1.039480e+07
                      PF        6.655482e+06
                      PG        1.228975e+07
                      SF        3.662924e+06
                      SG        4.639893e+06
Miami Heat            C         9.813480e+05
                      PF        1.019713e+07
                      SF        4.298409e+06
                      SG        7.123384e+06
New York Knicks       C         1.265000e+07
                      PF        3.128492e+06
                      PG        1.572360e+06
                      SF        8.452300e+06
                      SG        3.004155e+06
Oklahoma City Thunder C         6.303143e+06
                      PF        2.606520e+06
                      PG        9.382869e+06
                      SF        8.599621e+06
                      SG        3.207058e+06